---
title: "KV2 controles"
subtitle: "Dataset: `r params$datasetnaam`"
date: today
format: 
  html: 
    echo: false
    message: false
    self-contained: true
    page-layout: full
execute: 
  warning: false
  echo: false
params:
  pad_inputbestand: NA
  pad_controlesoutput: NA
  datasetnaam: NA
---

```{r packages_laden}
#| message: false
library(dplyr)
library(tidyr)
library(validate)
library(DT)
```

```{r data_inlezen}
validate_output <- readRDS(params$pad_controlesoutput)
# verwijder temp bestand
fs::file_delete(params$pad_controlesoutput)
```

Dit zijn de resultaten van de controles die zijn toegepast op het input bestand `r basename(params$pad_inputbestand)`.

### Samenvatting

```{r samevatting_tabel}
df_summary <- validate_output |> 
  select(description, controles) |> 
  unnest(controles)  |> 
  select(-name)


datatable(
  df_summary,
  rownames = FALSE,
  options = list(
    dom = "ltp",
    pageLength = 20, 
    autoWidth = FALSE,
    scrollX = FALSE
  )
) |> 
  formatStyle(columns = 1:ncol(df_summary), 
              fontSize = "80%")
```

### Foutive regels

```{r foutive_regels_tabel}
df_fouten <- validate_output |> 
  select(description, foutive_rijen) |> 
  unnest(foutive_rijen)  

datatable(
  df_fouten,
  rownames = FALSE,
  filter = 'top', 
  extensions = c("FixedColumns", "Buttons"),
  options = list(
    dom = "Bltp",
    pageLength = 10, 
    autoWidth = FALSE,
    scrollX = FALSE,
    fixedColumns = list(leftColumns = 2),
    buttons = c("csv")
  )
) |> 
  formatStyle(columns = 1:ncol(df_fouten), 
              fontSize = "80%")
```
