# Mappen
datamap  : "PAD NAAR INPUT MAP HIER INVULLEN"
werkmap  : "PAD NAAR WERK MAP HIER INVULLEN"
outputmap: "PAD NAAR OUTPUT MAP HIER INVULLEN"
# landbouwtelling
landbouwtellingpad: "PAD NAAR DE LANDBOUWTELLING SAV BESTAND HIER INVULLEN"
verblijfsplaatsenpad: "PAD NAAR DE VERBLIJFPLAATSEN SAV BESTAND HIER INVULLEN"
koppelbestand: "PAD NAAR KOPPELBESTAND NVWA RVO HIER INVULLEN" <- SYNTHETISCH BESTAND BESTAAT NOG NIET

# relatieve paden
logmap   : "log"
srcmap   : "src"
jpgmap   : "www"
sjablonenmap : "sjablonen"
configmap    : "config"
controlesmap : "controles"

# Script om mailfilterprobleem op te lossen - opent excelbestand en slaat op
open_en_sluit_excel_script : "open_en_sluit_excel.ps1" 

# Submappen
voorbereidingsmap : "1. Voorbereiding"
verwerkingsmap    : "2. Verwerking"
disseminatiemap   : "3. Disseminatie"

# Controle en correctie regels bestandsnamen
kv2_controles_rvo_slachtingen  : "kv2_controles_rvo_slachtingen.yml"
kv2_controles_rvo_slachthuizen : "kv2_controles_rvo_slachthuizen.yml"
kv3_correcties_rvo_slachtingen : "kv3_correcties_rvo_slachtingen.yml"

# Bestandsnamen
ctcr_aant_rdvl      : "analyse_aantallen_roodvlees_VWMD.xlsx"
ctcr_aant_wtvl      : "analyse_aantallen_witvlees_VWMD.xlsx"
ctcr_verd           : "analyse_aantallenverdelingen_VWMD.xlsx"
ctcr_gemg           : "analyse_gemiddeldegewichten_VWMD.xlsx"
ana_tijdreeksen     : "analyse_tijdreeksen_VWMD.xlsx"
ana_bijschattingen  : "analyse_bijschattingen_VWMD.xlsx"
out_eurostat        : "EuroStat.xlsx"
out_statline        : "7123SLAC.dat"
out_dsc_rdvl_kop    : "Roodvlees_"
out_dsc_rdvl_staart : "_(d).csv"
out_dsc_wtvl_kop    : "Witvlees_"
out_dsc_wtvl_staart : "_(d).csv"
out_contactpersonen : "contactpersonen.xlsx"
out_bio             : "Jaarcijfers_bio.csv"

# Opmaak analyse-Excelbestanden
kleur_vorige_vwmd    : 'gray88' # lichtgrijs
kleur_huidige_vwmd   : 'lightgoldenrodyellow' # lichtgeel
kleur_bijschatting   : 'red3' # mooi rood is niet lelijk
breedte_slachthuis   : 45
breedte_werkplek     : 10
breedte_diersoort    : 20
breedte_diersoortcat : 25
breedte_ind          : 12
breedte_trks_jaar    : 8
breedte_trks_mnd     : 15
breedte_eurostat_diersoortcat : 30
breedte_eurostat_cellen       : 15
breedte_contactpersonen_diersoortcat : 30
breedte_contactpersonen_cellen       : 20


# Constanten
verschil_huidige_mnd_eerste_mnd : -3
verschil_vwmd_historie_inicidenteel : -14

# Constanten voor de gewichten in kilogrammen van de dieren waarvan wij 
# geen maandelijkse gegevens van ontvangen van RVO, SBK kalf of een andere 
# instantie
eenhoevigen    : 225
geiten	       : 13
vleeskuikens   : 1.65
overige_kippen : 2.15
eenden	       : 2.1
duiven 	       : 0.4
fazanten	     : 0.8
ganzen	       : 3.0
kalkoenen   	 : 9.0
parelhoenders	 : 1.3
patrijzen	     : 0.4
struisvogels   : 30

# constanten voor Eurostat sdmx output const_sdmx
const_estat_dataflow  : "ESTAT:ANIP_MTSLS_M(1.0)"
const_estat_freq      : "M"
const_afronden_aantal : 3
const_afronden_gewicht: 3

# Databasezaken
dbdrivernaam : "SQL Server"
dbservernaam : "SERVERNAAM HIER INVULLEN"
databasenaam : "DATABASENAAM HIER INVULLEN"
databaseschema : "dbo"

# Database tabelnamen
tbl_dieren              : "tbl_dieren_kv2_kv3"
tbl_locaties            : "tbl_locaties_kv2_kv3"
tbl_dieren_op_locaties  : "tbl_dieren_op_locaties_kv2_kv3"
tbl_bio_locaties        : "tbl_biologische_locaties_kv3"
tbl_slachtingen         : "tbl_slachtingen_kv3"
tbl_microbase_rdvl      : "tbl_microbase_rdvl"
tbl_microbase_rdvl_def  : "tbl_microbase_rdvl_def" # alleen definitieve cijfers
tbl_microbase_wtvl      : "tbl_microbase_wtvl"
tbl_microbase_wtvl_def  : "tbl_microbase_wtvl_def" # alleen definitieve cijfers
tbl_microbase_verd      : "tbl_microbase_verd"
tbl_microbase_verd_def  : "tbl_microbase_verd_def" # alleen definitieve cijfers
tbl_microbase_gemg      : "tbl_microbase_gemg"
tbl_microbase_gemg_def  : "tbl_microbase_gemg_def" # alleen definitieve cijfers
tbl_microbase_gemg_sort : "tbl_microbase_gemg_sortering"
tbl_statbase_dsrt       : "tbl_statbase_dsrt"
tbl_statbase_dsrt_def   : "tbl_statbase_dsrt_def" # alleen definitieve cijfers
tbl_statbase_dcat       : "tbl_statbase_dcat"
tbl_statbase_dcat_def   : "tbl_statbase_dcat_def" # alleen definitieve cijfers
tbl_dsrt_en_dcat        : "tbl_diersoorten_en_diercategorieen"

## Skal dabatase
skal_dbdrivernaam : "SQL Server"
skal_dbservernaam : "SERVERNAAM HIER INVULLEN"
skal_databasenaam : "DATABASENAAM HIER INVULLEN"
skal_databaseschema : "SCHEMA HIER INVULLEN" skal_koppeling in ONT anders dbo

# Skal database tabelnamen
tbl_skal_certificaten: "tbl_certificaten"
tbl_skal_locaties: "tbl_locaties"
tbl_skal_activiteiten: "tbl_activiteiten"
tbl_skal_bedrijven: "tbl_bedrijven"

# BIO certificaten
rund_skal_hoofdsbi: ["01.41", "01.42", "10.1", "10.11", "10.13"]

# kolomnamen bestanden

na_waardes:
  ## I&R
  i_en_r_runderen_slachtingen: ["NA", ""]
  i_en_r_runderen_slachtplaatsen: ["NA", ""]

## I&R

kolomnamen:
  i_en_r_runderen_slachtingen:
    eld_code: 
      naam: "ELD_CODE"
      type: !expr readr::col_character()
    levens_nr:
      naam: "LEVENSNR"
      type: !expr readr::col_character()
    datum_geboorte:
      naam: "datum_geboorte"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_import:
      naam: "datum_import"
      type: !expr readr::col_date(format = "%d%b%Y")
    landcode_herkomst:
      naam: "LND_LANDCODE_HERKOMST"
      type: !expr readr::col_character()
    geslacht:
      naam: "GESLACHT"
      type: !expr readr::col_character()
    datum_eerste_afkalven:
      naam: "EERSTE_DATUM_AFKALVEN"
      type: !expr readr::col_date(format = "%d%b%Y")
    landcode_oorsprong:
      naam: "LND_LANDCODE_OORSPRONG"
      type: !expr readr::col_character()
    datum_slacht:
      naam: "datum_einde"
      type: !expr readr::col_date(format = "%d%b%Y")
    code_reden_einde:
      naam: "CODE_REDEN_EINDE"
      type: !expr readr::col_character()
    einde_oms:
      naam: "EINDE_OMS"
      type: !expr readr::col_character()
    ubn_0:
      naam: "UBN_0"
      type: !expr readr::col_character()
    bvg_type_0:
      naam: "BVG_TYPE_0"
      type: !expr readr::col_character()
    datum_ingang_0:
      naam: "datum_ingang_0"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_0:
      naam: "datum_einde_0"
      type: !expr readr::col_date(format = "%d%b%Y")
    ubn_3:
      naam: "UBN_3"
      type: !expr readr::col_character()
    bvg_type_3:
      naam: "BVG_TYPE_3"
      type: !expr readr::col_character()
    datum_ingang_3:
      naam: "datum_ingang_3"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_3:
      naam: "datum_einde_3"
      type: !expr readr::col_date(format = "%d%b%Y")
    ubn_2:
      naam: "UBN_2"
      type: !expr readr::col_character()
    bvg_type_2:
      naam: "BVG_TYPE_2"
      type: !expr readr::col_character()
    datum_ingang_2:
      naam: "datum_ingang_2"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_2:
      naam: "datum_einde_2"
      type: !expr readr::col_date(format = "%d%b%Y")
    ubn_1:
      naam: "UBN_1"
      type: !expr readr::col_character()
    bvg_type_1:
      naam: "BVG_TYPE_1"
      type: !expr readr::col_character()
    datum_ingang_1:
      naam: "datum_ingang_1"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_1:
      naam: "datum_einde_1"
      type: !expr readr::col_date(format = "%d%b%Y")
  # I&R geiten en schapen
  i_en_r_gaap_slachtingen:
    eld_code: 
      naam: "ELD_CODE"
      type: !expr readr::col_character()
    levens_nr:
      naam: "LEVENSNR"
      type: !expr readr::col_character()
    dst_code:
      naam: "DST_CODE"
      type: !expr readr::col_integer()
    datum_geboorte:
      naam: "datum_geboorte"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_import:
      naam: "datum_import"
      type: !expr readr::col_date(format = "%d%b%Y")
    landcode_herkomst:
      naam: "LND_LANDCODE_HERKOMST"
      type: !expr readr::col_character()
    geslacht:
      naam: "GESLACHT"
      type: !expr readr::col_character()
    landcode_oorsprong:
      naam: "LND_LANDCODE_OORSPRONG"
      type: !expr readr::col_character()
    datum_slacht:
      naam: "datum_einde"
      type: !expr readr::col_date(format = "%d%b%Y")
    code_reden_einde:
      naam: "CODE_REDEN_EINDE"
      type: !expr readr::col_character()
    einde_oms:
      naam: "EINDE_OMS"
      type: !expr readr::col_character()
    ubn_0:
      naam: "UBN_0"
      type: !expr readr::col_character()
    bvg_type_0:
      naam: "BVG_TYPE_0"
      type: !expr readr::col_character()
    datum_ingang_0:
      naam: "datum_ingang_0"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_0:
      naam: "datum_einde_0"
      type: !expr readr::col_date(format = "%d%b%Y")
    ubn_3:
      naam: "UBN_3"
      type: !expr readr::col_character()
    bvg_type_3:
      naam: "BVG_TYPE_3"
      type: !expr readr::col_character()
    datum_ingang_3:
      naam: "datum_ingang_3"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_3:
      naam: "datum_einde_3"
      type: !expr readr::col_date(format = "%d%b%Y")
    ubn_2:
      naam: "UBN_2"
      type: !expr readr::col_character()
    bvg_type_2:
      naam: "BVG_TYPE_2"
      type: !expr readr::col_character()
    datum_ingang_2:
      naam: "datum_ingang_2"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_2:
      naam: "datum_einde_2"
      type: !expr readr::col_date(format = "%d%b%Y")
    ubn_1:
      naam: "UBN_1"
      type: !expr readr::col_character()
    bvg_type_1:
      naam: "BVG_TYPE_1"
      type: !expr readr::col_character()
    datum_ingang_1:
      naam: "datum_ingang_1"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_1:
      naam: "datum_einde_1"
      type: !expr readr::col_date(format = "%d%b%Y")
  # Slachtplaatsen
  i_en_r_runderen_slachtplaatsen:
    ubn:
      naam: "UBN"
      type: !expr readr::col_character()
    bvg_type:
      naam: "BVG_TYPE_BEDRIJFSVESTIGING"
      type: !expr readr::col_character()
    bvg_postcode_plaatscode:
      naam: "BVG_POSTCODE_PLAATSCODE"
      type: !expr readr::col_character()
    bvg_postcode_lettercode:
      naam: "BVG_POSTCODE_LETTERCODE"
      type: !expr readr::col_character()
    bvg_huisnummer:
      naam: "BVG_HUISNUMMER"
      type: !expr readr::col_integer()
    bvg_huisnummer_toevoeging:
      naam: "BVG_HUISNUMMER_TOEVOEGING"
      type: !expr readr::col_character()
    bvg_straatnaam:
      naam: "BVG_STRAATNAAM"
      type: !expr readr::col_character()
    bvg_plaatsnaam:
      naam: "BVG_PLAATSNAAM"
      type: !expr readr::col_character()
    x_coordinaat:
      naam: "X_COORDINAAT"
      type: !expr readr::col_integer()
    y_coordinaat:
      naam: "Y_COORDINAAT"
      type: !expr readr::col_integer()
    status:
      naam: "STATUS"
      type: !expr readr::col_character()
    datum_ingang:
      naam: "datum_ingang"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde:
      naam: "datum_einde"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_ingang_dst:
      naam: "datum_ingang_dst"
      type: !expr readr::col_date(format = "%d%b%Y")
    datum_einde_dst:
      naam: "datum_einde_dst"
      type: !expr readr::col_date(format = "%d%b%Y")
    brs_nummer:
      naam: "BRS_NUMMER"
      type: !expr readr::col_character()
    kvk_nr:
      naam: "KVK_NR"
      type: !expr readr::col_character()
    naam:
      naam: "NAAM"
      type: !expr readr::col_character()
    aantal:
      naam: "aantal"
      type: !expr readr::col_integer()
  # landbouwtelling
  landbouwtelling:
    relnr: 
      naam: "relnr"
      type: "character"
    bvg_postcode_plaatscode:
      naam: "J[0-9]{2}pcnum"
      type: "character"
    bvg_postcode_lettercode:
      naam: "J[0-9]{2}pclet"
      type: "character"
    bvg_huisnummer:
      naam: "J[0-9]{2}huisnr"
      type: "numeric"
    bvg_huisnummer_toevoeging:
      naam: "J[0-9]{2}hnrtoev"
      type: "character"
    skalnr_lbt: 
      naam: "W[0-9]{2}ZZ.1000"
      type: "character"
  # verblijfsplaatsen
  verblijfsplaatsen:
    relnr:
      naam: "Relnr"
      type: "character"
    ubn:
      naam: "UBN_NUMMER"
      type: "character"
